### ISSUE TITLE
crawling error

### ISSUE THREAD

**Issue by hugt** [VShawn/tutiempo_crawler#1]
Hi Shawn,
Thanks for your wonderful tool. I currently encounter this error when trying to craw data from tutiempo.net
 SSLError: HTTPSConnectionPool(host='en.tutiempo.net', port=443): Max retries exceeded with url: /climate/Hanoi/1/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
Could you please help me to fix the error.

Thanks

**Comment by VShawn** [comment]
plz set verify to false, and then it would works.

https://github.com/VShawn/tutiempo_crawler/blob/master/tutiempo_crawler.py#L17

https://github.com/VShawn/tutiempo_crawler/blob/master/base_monthlyclimate.py#L38
