### ISSUE TITLE
请教如何下载多年的数据？

### ISSUE THREAD

**Issue by Baiyssy** [VShawn/tutiempo_crawler#3]
请教，如果我需要下载多年的数据，demo.py里的year = 2018应该改成什么？
谢谢！

**Comment by VShawn** [comment]
https://github.com/VShawn/tutiempo_crawler/blob/master/demo.py#L42-L56

在这里，外面包裹一个循环，每轮循环都给 `year` 赋一个新值

你仔细看可以发现，这段获取一年数据其实也是一个月一个月地获取的，最后把12个月数据合并生成了全年的数据。
